name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --force

      - name: Build React app
        run: npm run build

  deploy:
    runs-on: ubuntu-20.04

    needs: build

    steps:
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          host: ftp://teamxmark.com
          user: u750630823
          password: Koko@ak4
          port: 21
          local-dir: build
          remote-dir: /public_html
